### ISSUE TITLE
Show file upload progress

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#551]
## Definition
As a user who is uploading an attachment
I want to see an upload progress indication
So I have an estimate of how long the operation will take

## Constraints
This story depends on #548 being done.

## UI
![image](https://cloud.githubusercontent.com/assets/350155/11749650/33a5d3a6-a016-11e5-91c5-deb3e181f94c.png)
Progressing bar background color: $light_blue (#3DABC4)

# Open Questions
Q: What happens if the user closes the email pane during the upload? Does it keep uploading in the background? Does it stop? Does it prompt the user to decide what to do?

**Comment by fbernitt** [comment]
Works great!

As discussed, the upload looks slightly different now (and there can be only one upload at any given time, as the jquery plugin seems to queue them up).

**Comment by albogabriel** [comment]
Hey @felixhammerl and @fbernitt,

Are we not showing the file name while the upload happens anymore?

I'd consider this very important for the feature usability - it's important for the user to be able to know what file is being uploaded and it's size for error prevention and system status.

(Please disregard this if that is not the case - I'm basing this in the screenshot from Felix's comment on #552)

**Comment by felixhammerl** [comment]
On Feb 3, 2016 20:03, "Gabriel Albo" <notifications@github.com> wrote:
>
> Hey @felixhammerl and @fbernitt,
>
> Are we not showing the file name while the upload happens anymore?

Well, we never did in the first place :)
Nope, I removed that because it removes the need for dynamic DOM elements.

> I'd consider this very important for the feature usability - it's
important for the user to be able to know what file is being uploaded and
it's size for error prevention and system status.

It's on the master, you can try it out.

You can only upload one file at a time, so IMHO it's not that big a deal.
Should that not be the case, I can put it back in tomorrow.

**Comment by felixhammerl** [comment]
![screen shot 2016-02-04 at 11 25 34 am](https://cloud.githubusercontent.com/assets/1818340/12812725/fefa70e6-cb33-11e5-99c0-f18d6466de84.png)

Is that better?
