### ISSUE TITLE
The UA API should be able to handle multiple users

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#576]
In order to have the user agent working for multiple users, we need the API to support multiple sessions and be able to server more than one user

**Comment by bwagnerr** [comment]
There's a branch multiuser that enables you to run two APIs (one for each user), that can be used as a starting point

**Comment by fbernitt** [comment]
To run the user agent in multi-user mode, start it like this:

```bash
# start user agent in the vagrant box

pixelated-user-agent --debug --host 0.0.0.0 --multi-user --provider providername
```
Then just connect to the user agent using your browser (http://localhost:3333/) and you should see a login screen.

**Comment by giovaneliberato** [comment]
I could login into two different accounts. Login and indexing works well, but when I started to send mails I notice some things

#### From the same provider:
The key from one isn't being removed from attachments

<img width="812" alt="screen shot 2016-01-28 at 3 55 24 pm" src="https://cloud.githubusercontent.com/assets/2964631/12653656/ad04e548-c5d7-11e5-83ca-e79423900ea8.png">

It feels strange that the key was attached. It lead to the following error when replying that I assume occurred because it could not look for the keychain and tried to import the attached key.

```
pixelated.adapter.services.mail_sender.MailSenderException: ('Failed to send mail to all recipients', {u'xxxxx@wazokazi.is': None, u'gliberat1@dev.pixelated-project.org': <twisted.python.failure.Failure exceptions.AssertionError: Found more than one key for address gliberat1@dev.pixelated-project.org!>})
```

.
#### From different providers
It isn't able to verify signatures
<img width="806" alt="screen shot 2016-01-28 at 3 55 00 pm" src="https://cloud.githubusercontent.com/assets/2964631/12653807/4863bdfc-c5d8-11e5-9291-09e2f0b85cf4.png">

**Comment by fbernitt** [comment]
Is this something that only happens with the multi-user setup? Or is it a general problem?

**Comment by giovaneliberato** [comment]
@fbernitt just tested with --multi-user

**Comment by giovaneliberato** [comment]
@fbernitt It's also happening on a non multi-user setup. Can you reproduce this or do you want me to take a look?

**Comment by fbernitt** [comment]
If its on both types of setup, I think it would be best to create a new issue for this
