### ISSUE TITLE
Should show interstitial when login takes some time

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#583]
Like the dispatcher, the user agent in multi uesr mode should show a loading screen when it takes time to initialize the user agent and do the initial sync.

**Comment by mnandri** [comment]
There is still a bit of lag (1 or 2 seconds) before the interstitial is loaded. The reason is we create the leap and soledad session before we load it.
To move forward we have to balance:
* Loading the interstitial straight after leap auth is done, it will be faster
* The user having no feedback if anything goes wrong from then onwards.

**Comment by giovaneliberato** [comment]
It works! :dancers:
