### ISSUE TITLE
Make installation of useragent easier

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#593]
This is the current recommended installation from the README:

```
Clone the repository:

    git clone https://github.com/pixelated-project/pixelated-user-agent.git
    cd pixelated-user-agent

From the project root folder, set up the vagrant machine:

    vagrant up

After this is done, you can log into the machine and view project root folder with:

    vagrant ssh
    cd /vagrant

Then run the setup:

    cd /vagrant/service
    ./go setup

From here on you can run the tests for the UI by going to the **web-ui** folder or for the REST API by going to the **service** folder:

    cd /vagrant/web-ui
    ./go test

    cd /vagrant/service
    ./go test

To run the user agent:

$ pixelated-user-agent --host 0.0.0.0 -lc /vagrant/service/pixelated/certificates/dev.pixelated-project.org.ca.crt
...
```

We should make this a lot easier for the hacknight, ideally a onliner like we have in puppet-pixelated.

**Comment by pereiragislene** [comment]
1. On CONTRIBUTING.MD:
 * The link "issues labeled 'Beginner'" is pointing to the wrong path (because git adds blob to the relative path. We need to set the entire path to https://github.com/pixelated/pixelated-user-agent/labels/Beginners).

2. On README.MD: 
 * All the (How To) are not working
 * The link "restart the server" is not working

**Comment by pereiragislene** [comment]
I've fixed the Contributing.md file. 
@mnandri: could you please fix the links on the README.md file, since you have more context on how they should behave?
