### ISSUE TITLE
Attachment: PNG content type is messed up and inconsistent

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#596]
I opened the mail @giovaneliberato sent about "Pixelated spreading all over the world", and tried to open the attached PNG.

* On Ubuntu/Firefox, it says the application content type is an PDF (see first screenshot)
* On Ubuntu/chromium, it forces me to download it
* On MacOs/Firefox, it says the content type is 'force-download' (see second screenshot)
* On MacOS/chrome, it also forces the download

**Comment by varac** [comment]
![p4qieeq](https://cloud.githubusercontent.com/assets/488213/12883587/3369d02e-ce59-11e5-986f-4031c4c02706.png)

**Comment by varac** [comment]
![macos_chrome](https://cloud.githubusercontent.com/assets/488213/12883630/5ea55a88-ce59-11e5-8f13-29ed4f619902.png)

**Comment by cz8s** [comment]
hmm. still strange. My browser says, this is a mp3. And it can't handle filenames with spaces:
![selection_003](https://cloud.githubusercontent.com/assets/369402/12978208/d8f33936-d0cf-11e5-8553-220178addc48.png)

**Comment by felixhammerl** [comment]
There is a slight difference between what happens on wazokazi (w/ dispatcher) versus what happens on a local env (w/o dispatcher).

With dispatcher:
```
Content-Disposition:"attachment; filename=Screen Shot 2016-02-09 at 10.24.10 AM.png"
```

Without dispatcher:
```
Content-Disposition:"attachment; filename="Screen Shot 2016-02-09 at 10.24.10 AM.png""
```

The dispatcher seems to remove the quotes around the file name in the HTTP response, hence the FF bug. Since this would require fixing the dispatcher (which will be scrapped anyway), I'd label it as a known wontfix.

**Comment by cz8s** [comment]
agreed. It works on my local installation. Lets launch this then. The dispatcher is almost gone anyway
