### ISSUE TITLE
include usernames in log

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#601]
since all users now run inside the same user-agent, the logs do not contain any information
about the user anymore. We should include the username in the logs to help debugging

**Comment by varac** [comment]
+1 it would really help debugging the several bug that we are hunting.

however i would feel very uneasy with logging usernames by default.
Either we make it configurable, and default it to *not* log usernames/uuids, only in debug mode, or if we log by default, only the uuids should be included (and we would need an easy way of converting uuids to users when parsing the logs).

**Comment by deniscostadsc** [comment]
@mnandri 
Are you going to implement just uuid?

**Comment by mnandri** [comment]
I"m putting this on hold, for now... because there is no way  (or at least, that I can think of) to add uuids from the libraries logs without explicitly doing so, from those libraries themselves.
We can add them from the user-agent logs but that really accounts for less than 5% of the logs.
Majority of the logs comes from soledad (and twisted) and we can add those explicitly from soledad as it knows about uuids but only the core api (and a few modules) are aware of them. 
We need to have a discussion with leap if it makes sense to send that additional information, just to log them out.

**Comment by varac** [comment]
@mnandri did you discuss this with the LEAP devs so we could start to implement ?

**Comment by anikarni** [comment]
Closed due to inactivity
