### ISSUE TITLE
[Bug] Emails leak  across user  accounts

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#674]
During the load test this morning (Apr 01, 2016)... Felix received emails that we were sending to the load tests users...
He should not have seen nor received those.

The tests were conducted on localhost but used dev as the provider.

**Comment by felixhammerl** [comment]
Screenshot from the situation naval was talking about. Check out the recipients, those mails were never sent to my account. O.o

![screen shot 2016-04-01 at 12 21 16 pm](https://cloud.githubusercontent.com/assets/1818340/14208446/b4ee01ca-f81f-11e5-9a56-5bb4773f4f6d.png)

**Comment by varac** [comment]
During the platform install party today we experienced the same behaviour that each of us saw mails addressed to someone else randomly.

**Comment by shyba** [comment]
I don't have enough context ATM, but I would start by checking the sync
event handler on LEAP mail (if it's setting and capturing user ID
properly).
*If* SOLEDAD is firing it without a user ID or LEAP mail is capturing
without filtering, then bad stuff can happen.
This bug is awesome for it's amount of possible error places and I would
like to keep informed on how it's going, unless it's an easy fix.
Em 2 de abr de 2016 2:39 PM, "varac" <notifications@github.com> escreveu:

**Comment by kalikaneko** [comment]
This kind of bug was one of my fears in the multi-tenant scenario. This might be a warning about dangers of shared state without strong layers of isolation :/
ready to help debug with the components I know most.

**Comment by kalikaneko** [comment]
I was thinking that maybe one precautionary measure here might be to put some kind of assert in the msg_collection.add_msg, to check that we don't add messages to an inbox which aren't addressed to the user the mailbox/collection is configured with. it's not going to solve the problem, but it might save the day in case a catastrophic bug like this one slips again in production.

**Comment by cacarrara** [comment]
Just to let you know, I got this same error on staging today.

Screenshot logged with alice user and inbox with emails sent to behave-testuser.

![Uploading image.png…]()

**Comment by varac** [comment]
oh, this got reopened again ?

**Comment by cacarrara** [comment]
@varac we reopened it specially to track the [Soledad PR](https://github.com/leapcode/soledad/issues/315) which is still open.

**Comment by varac** [comment]
@cacarrara i know external ppl are concerned about this bug, so it would be good to clarify if the bug itself is closed (which is what my perception is), and this issue is a reminder to not forget about the pull req mentioned above (that does what exactly) ? 
In other words, does the useragent still leak mail at this moment ?

**Comment by bwagnerr** [comment]
The bug is fixed, the PRs are mainly to ensure this doesn't happen again to anyone using leap mail and soledad (including us).

There is no leakage of mails on the current build

**Comment by varac** [comment]
@bwagnerr thx !
