### ISSUE TITLE
[bug] attachments not working

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#679]
while trying to attach a file,
after clicking the "open" button on the file selection window... the attachment is briefly seen and disappears from the attachment list.
When clicking the send button, no attachment is received.

**Comment by mnandri** [comment]
this is already deployed... so either needs to be fixed or the feature be reverted!

**Comment by thaissiqueira** [comment]
It works! But I think to finish this task we need tests. Because if it breaks again we won't be able to see it is broken.

I think we need at least add new validation steps on functional tests on puppet pixelated in order to close this task.

**Comment by cacarrara** [comment]
I agree with @thaissiqueira. On `puppet-pixelated` functional tests I think is important run tests to validate that attachments are sent and received successfully. Seems that it's not tested properly there.

However the css issue that we had here should be tested and validated on `web-ui/tests`. Currently there is a test on it called `should add attachment to the list based on uploadedAttachment event`. I didn't analyse what it's doing, but looking for the test name seems that it should get this kind of error. If this specific test can't cover it, maybe we can try to write a new one on this layer.

**Comment by gusandrews** [comment]
I'm wondering if this was related to an earlier issue. While I was user testing in March, if users added enough attachments the Send button would scroll off the bottom of the screen. I don't see that happening now (I just came back to test it, as I am writing up my user test results for you all), so I'm wondering if whatever fix was made started making attachments disappear off the screen? Then again, I can't replicate the scrolling problem because attachments aren't staying on screen, so...

**Comment by tuliocasagrande** [comment]
I tested it and it's working locally (I had to run `./go setup` first).
However, it's no working on our CI environment. Anyone has any thoughts about that?

**Comment by gusandrews** [comment]
I take it this hasn't been pushed to the online demo yet? I tried it and it's still losing attachments.

**Comment by cacarrara** [comment]
@gusandrews now it's pushed to https://try.pixelated-project.org:8080. :)
