### ISSUE TITLE
Migrate from leap_auth to bonafide

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#698]
Bitmask core requires bonafide, the new leap authenticator.
Bonafide already supplements the leap_auth functionality.

**Comment by cacarrara** [comment]
Sorry, but is still not clear to me why exactly we have to "migrate" to bonafide. Could you please talk a little bit more the reason for it?

Thanks.
cc @bwagnerr

**Comment by deniscostadsc** [comment]
@cacarrara 

We wrote some libraries to encapsulate LEAPs API. Now they have a library for authentication. So, we need to remove ours to use theirs. Bonafide is library fo registration, authentication, and discover the providers.

**Comment by bwagnerr** [comment]
@cacarrara What @deniscostadsc said. Also leap auth is blocking, that means that every new login blocks the reactor and makes it unresponsive for some small time, that is a performance cost it would be better not to have

**Comment by cacarrara** [comment]
Thanks, @deniscostadsc.

However, what I could understand was that Bonafied (as decribed here https://leap.se/en/docs/design/bonafide) is an API (more than a protocol). So we can consume that API according to our needs.

I also verified that LEAP folks have created a repository called bonafied (https://github.com/leapcode/bonafide). In its readme it's defined as "a client". Of course this client is developed according to bitmask needs (twisted things, etc) and not necessarily cover needs (and limitations) of Pixelated User Agent.

Currently the leap_auth lib seems to cover our needs. I didn't look into it very well, but I saw that it already uses SRP, for instance. So, if we need to change anything because any API change, why don't change current leap_auth?

@bwagnerr, the block thing seems to be a good reason. So, we're not changing because any change from LEAP side, but because we want to improve performance. Right?

**Comment by bwagnerr** [comment]
The change is twofold, leap is currently using the user agent also, so we are impacting them with that. If we change, we wouldn't have to care about changes to the authentication protocol, would be one less library to maintain

**Comment by cacarrara** [comment]
@bwagnerr how are we impacting leap?

Just adding something that came to my mind now. Is the current user agent auth method (blocking) a real issue? Have we measured that? Just trying to understand and justify the efforts.

**Comment by bwagnerr** [comment]
We haven't measured that yet and while that might be a good side effect, the main reason is not to have a different code base and one more package for authentication.

**Comment by kalikaneko** [comment]
I have measured that:
https://gist.github.com/kalikaneko/9e6aa00efc41f1881a61255c245c48bf

notice that bloking causes contention in the threadpool.

**Comment by tuliocasagrande** [comment]
We decided to restart this issue after the conclusion of #772.

**Comment by tuliocasagrande** [comment]
The commits that matter are:

Implements bonafide to replace leap.auth 1114cfcfba7b67b9d3e6238ce9dc2ab578060f93

multi_user_client now accounts for the login process  8e7b7d53a6bef24ced29549746699f26595f4c71

[#698] Add default user to the integration test client  13190c695c1b58a1f28d2c1533c36c0353b0a438

**Comment by varac** [comment]
sorry i moved the wrong issue

**Comment by deniscostadsc** [comment]
Should we remove this line from requirements?

```
https://github.com/pixelated/pixelated-user-agent/blob/master/service/requirements.txt#L11
```

**Comment by deniscostadsc** [comment]
I wrote a comment on this commit:

https://github.com/pixelated/pixelated-user-agent/commit/8e7b7d53a6bef24ced29549746699f26595f4c71#commitcomment-19117406

**Comment by bwagnerr** [comment]
@deniscostadsc We can't remove leap.auth yet because a lot of our code is expecting that credential format, we are not using it to authenticate anymore, but to hold the credentials. That would be a bigger and more thorough change

**Comment by deniscostadsc** [comment]
> @deniscostadsc We can't remove leap.auth yet because a lot of our code is expecting that credential format, we are not using it to authenticate anymore, but to hold the credentials. That would be a bigger and more thorough change

OK!
