### ISSUE TITLE
Display the sender’s name

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#723]
Recently some usability tests and analysis were done by Pixelated members and supporters, usability experts advised us to display the sender’s name so is easy to scan and determine who you are talking to: 

<img width="686" alt="screen shot 2016-06-17 at 5 56 42 pm" src="https://cloud.githubusercontent.com/assets/6019419/16164498/e236ebde-34b4-11e6-88ba-210643ddda62.png">

**Comment by re-nobre** [comment]
Hey, @SweetVirginia !
I think it's not a interface solution because when I receive an email from other servers I can see the name of the sender. Look:

<img width="821" alt="screen shot 2016-06-20 at 10 18 09 am" src="https://cloud.githubusercontent.com/assets/2657059/16187413/7de5b3e0-36d0-11e6-8d08-12354dc178aa.png">

What do you think?

**Comment by SweetVirginia** [comment]
Wow! That's right. Then we have to think a better solution at creating account flow, such as ask for an username or something like that.

**Comment by re-nobre** [comment]
So, I think is better we remove the Hacknight labels for now, right?

**Comment by re-nobre** [comment]
I talked with @SweetVirginia and we will analyse all the UX proposals in a different place and create the issues when we will work on it.

For all the UX/UI proposals and feedbacks, take a look [here](https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

I'm closing this issue now.
