### ISSUE TITLE
Use newer version of nodejs

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#737]
here's how I did it on debian jessie:

```
apt install apt-transport-https
curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo "deb https://deb.nodesource.com/node_6.x jessie main" > /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/node_6.x jessie main" >> /etc/apt/sources.list.d/nodesource.list
apt update
```

put this in `/etc/apt/preferences.d/nodejs`:

```
Package: nodejs
Pin: release o=Node Source
Pin-Priority: 999
```

then:

```
apt install nodejs
```

**Comment by cacarrara** [comment]
Well, I've tried do this, but I don't know why the following error was being raised: http://paste.debian.net/772570/

We can see the proper version of NodeJS and npm in the logs.

I'm backing it to ready for now because I will not be able to deal with it.

**Comment by mnandri** [comment]
I've run it on my box.
It's flawless.

If it complains about node_modules folder existing, you may just want to remove it. It should be recreated anyway...
@cacarrara

**Comment by tuliocasagrande** [comment]
On jessie-pixelated-user-agent-packaging we are still facing the syntax error:

```
> node config/imagemin.js

).then(files => {
           ^
SyntaxError: Unexpected token >
 at Module._compile (module.js:439:25)
 at Object.Module._extensions..js (module.js:474:10)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:312:12)
 at Function.Module.runMain (module.js:497:10)
 at startup (node.js:119:16)
 at node.js:906:3
```

Shouldn't the node upgrade fix this error?

**Comment by mnandri** [comment]
The short answer is no.

The long answer is... because we're using pbuilder with basetgz for distribution pre-building. It includes the "normal" jessie node, which is 0.10.29... 
when the package is build, it will chroot to that (and not use the system's newly upgraded node) and hence will fail.

We need to update the pbuilder basetgz to have the right node version... It's just not very clear where in our pipeline do we do that... the files are /var/go/pbuilder though but where are they generated is not very clear to me...
I remember @cz8s vaguely telling me about some base image for go-agents... not sure... but I think that's a good place to start...

**Comment by bwagnerr** [comment]
@mnandri hey, the base.tgz is manually made and updated when we need it, as far as I know

**Comment by cz8s** [comment]
Nope. Its done by puppet

**Comment by tuliocasagrande** [comment]
> (user-agent-venv)vagrant@leap-jessie:~$ node --version
v6.2.2

LGTM 👍
