### ISSUE TITLE
Is a super simple approach for signatures and encryption possible?

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#758]
"As an journalist using Pixelated, I expect it to handle automatically this privacy/security features it says it has so I don't bother with tech complicated stuff." 

#### Hypothesis:
What really matters is if people's communication is safe or not, if people can trust their privacy in their email provider. It's not important how. 

#### Why:
Our users are not aware of the concepts of signatures, encryption, keys, etc. They may heard of cryptography (thanks WhatsApp), but that doesn’t mean they know what it is and how it works. 
Why should they learn concepts like Signed and Encrypted since security is the outcome? 

#### A bold suggestion: 
what if Pixelated have only 2 states? Secure and Insecure*. But how? Well, that’s the challenge. 

*namings are open.
___
#### Below some crazy ideas

![approach](https://cloud.githubusercontent.com/assets/6019419/17603005/9154362a-5fe5-11e6-9d5e-1ee959817c45.png)
![emails and group alias](https://cloud.githubusercontent.com/assets/6019419/17603006/91547072-5fe5-11e6-844c-8ecec643e058.png)
![public mailing lists](https://cloud.githubusercontent.com/assets/6019419/17603008/91598b8e-5fe5-11e6-851c-7346f2fada3e.png)
![sending](https://cloud.githubusercontent.com/assets/6019419/17603007/91586326-5fe5-11e6-862f-4add11f48342.png)

**Comment by cz8s** [comment]
If I understand correctly, we will only display changes in communication.
So if I always communicate with someone in plaintext, it will stay green.
But if I receive an unencrypted email from someone who used to send me encrypted emails before,
it will be red. correct?

I like it that it doesn't scare people just because they received an unencrypted spam email.

You suggestion depends on multiple emails being exchanged before it starts to work.
This might not be helpful for a journalist who might only recieve one email from an informant.
Do we have a way to tell the journalist about the properties of this one email?

And: I think there really are two states a mail can have: encrypted and signed.
These are two totally distinct properties and it might make sense to handle them differently.

If a mail is signed, I can be sure that it was sent by the sender.
If a mail is encrypted, I can be sure that nobody read the mail, but I don't know who sent it.

Usually I only care about one of these features depending of the content:
If someone sends me a password, I don't care if the sender is correct, as long
as the password works and nobody read it :)
If someone sends me a contract, I don't care if someone else read it as long as I can
be sure that it was sent by the correct person.
Very seldomly I need both features at the same time, no?

The way it works in this proposal doesn't give the user a way to see these properties.

I think your proposal makes a lot of sense for people that communicate regularly with each other.
If we add some other indication for the first email exchange, this might become awesome.

**Comment by olabini** [comment]
If I remember correctly, a plaintext email will not get a green, it will just have no indication at all. So there are really three states. 

If a journalist only ever receives one single email from a source, there is no baseline to understand that email in context, so what properties would you like to be able to display in those circumstances?

The problem with signatures is that signature failures usually correlate to unintentional modification, since an intentional modification would just strip the full signature. Thus, displaying signature information separately from the encryption information actually doesn't give the end user more information. That's the main reason we decided to simplify to just previous baseline behavior.

**Comment by SweetVirginia** [comment]
Hey, even though there's green check marks on the schemes it doesn't mean it will be at the User Interface. There hasn't been a decent UI study and discussion yet :) 

What we need now is discuss whether we should try to merge (or hide) the concepts of signature and encryption like other popular services who "sell" encryption, or if is valid to show and educate about these concepts. I am definitively inclined to the first option. 

--

> 
> Usually I only care about one of these features depending of the content:
> If someone sends me a password, I don't care if the sender is correct, as long
> as the password works and nobody read it :)
> If someone sends me a contract, I don't care if someone else read it as long as I can
> be sure that it was sent by the correct person.
> Very seldomly I need both features at the same time, no?

I really like this, but I suspect that's way ahead of the average user mindset. Actually, there is a very good thing to ask people about 😃 

On "Multiple Receivers" there's a draft about "recipient status" that can be used to show how reliable your contact is. But Ola gave one good reason I can't remember for that not being as effective. 


--

> This might not be helpful for a journalist who might only recieve one email from an informant.
> Do we have a way to tell the journalist about the properties of this one email?

We thought that when an email is signed and encrypted it doesn't matter what the communication was before, it will be always "secure". Since they will invite sources to Pix to exchange information, the messages will be signed and encrypted by default, so I think we covered that.

**Comment by SweetVirginia** [comment]
Things to have in mind:

What’s the best UI strategy? What to show or not to show the user?
What will be the instructions for them in case there’s something wrong?(What can possibly go wrong?)
Expired/Revoked keys, how to show?
How will public keys be found by people outside their provider? Can we do it manually if that’s the case?

**Comment by thaissiqueira** [comment]
@SweetVirginia let's close this issue and open a new one to start prototype some options?
What do you think?

**Comment by SweetVirginia** [comment]
Sure. I'll do that :)

**Comment by SweetVirginia** [comment]
https://github.com/pixelated/pixelated-user-agent/issues/760
