### ISSUE TITLE
Investigate where the ~5s of login-leap-session is spending

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#772]
## What
After adapting the create_new_session (#762), we saw that the login-leap-session is taking around 5 seconds. It is still a long time for a simple task.

We want to understand what is happing during this time. 

## Definition of done
- List what is happening in this ~5s of login-leap-session

**Comment by olabini** [comment]
Maybe this is the right time to actually set up some expectations for performance in terms of user experience? If the contention issue actually is gone from login, there seems to be two big next chunks of work - make sure there is no contention anywhere else, and to work on general performance. @SweetVirginia, thoughts?

**Comment by bwagnerr** [comment]
Some findings, we'll update this as we go:

Authenticate
---

Depending on the internet connection, the authentication process (with http requests) can take from 20% to 60% of the login time:

```python
3.48846 leap-session-authenticate 
4.32830 leap-session-create 
7.81696 leap-session 
0.11681 setup-user-services
---
2.44381 leap-session-authenticate
5.97112 leap-session-create
8.41513 leap-session
0.12235 setup-user-services
---
9.01044 leap-session-authenticate 
6.14727 leap-session-create 
15.15791 leap-session 
0.11451 setup-user-services
```

These requests are:
- Regular requests from the requests library and don't use the twisted http library
- They already run on a thread so they are not blocking the main loop

**Comment by bwagnerr** [comment]
Authentication Speed (Bonafide vs. Leap Auth)
---

We tested quickly to see if using bonafide would improve the authentication speed and the results are below:

Leap auth average: **1.91s**
Bonafide average: **2.61s**

That means migrating to bonafide (that uses async http requests) won't give us improvements over running leap.auth on threads for now.

We'll move on to the leap-session-create to check if there are any easy pickings to improve the login speed

(@kalikaneko, you might also be interested in these results)

---

Raw data below:

**With bonafide**
```
3.00056 login-leap-session-authenticate
2.59804 login-leap-session-create
5.59874 login-leap-session
# ---
2.42000 login-leap-session-authenticate
2.65806 login-leap-session-create
5.07821 login-leap-session
# ---
2.41808 login-leap-session-authenticate
2.63845 login-leap-session-create
5.05691 login-leap-session
```
**With leap.auth**
```
2.09822 login-leap-session-authenticate 
2.92649 login-leap-session-create 
5.02489 login-leap-session 
#---
1.85527 login-leap-session-authenticate 
2.61670 login-leap-session-create 
4.47219 login-leap-session 
#---
1.83458 login-leap-session-authenticate 
3.13648 login-leap-session-create 
4.97124 login-leap-session
```

**Comment by kalikaneko** [comment]
Interesting. Can you point me to the code producing these results?
From my machine, using bitmaskctl I get ~2 seconds for the authentication (i'm 200ms away from the test server).

```
2016-09-01T17:21:26-0400 [ZMQ] Provider already initialized
2016-09-01T17:21:26-0400 [ZMQ] on_passphrase_entry: New Soledad Instance: foo2@mail.bitmask.net
2016-09-01T17:21:26-0400 [ZMQ] Adding a new Keymanager instance for foo2@mail.bitmask.net
2016-09-01T17:21:26-0400 [ZMQ] Provider already initialized
2016-09-01T17:21:26-0400 [ZMQ] AUTH for foo2@mail.bitmask.net
2016-09-01T17:21:26-0400 [ZMQ] POST to https://api.mail.bitmask.net:4430/1/sessions
2016-09-01T17:21:26-0400 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7fb3a45dc758>
2016-09-01T17:21:26-0400 [-] Core: Key not found. Generating key for foo2@mail.bitmask.net
2016-09-01T17:21:27-0400 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] PUT to https://api.mail.bitmask.net:4430/1/sessions/foo2
2016-09-01T17:21:27-0400 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7fb3a45957a0>
2016-09-01T17:21:27-0400 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7fb3a45dc758>
2016-09-01T17:21:28-0400 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] POST-AUTHENTICATE: took 2.000357 seconds
```

On the other hand, I would check if the above holds true for several concurrent sessions being created (in a number > than the number of threads in the threadpool).

**Comment by bwagnerr** [comment]
@kalikaneko 
The change implementing this is here: https://github.com/pixelated/pixelated-user-agent/tree/implement_bonafide

**Comment by bwagnerr** [comment]
Okay, going deeper into the login time we have:

```python
4.76631 login-leap-session
2.82042 login-leap-session|create
2.65271 login-leap-session|create|first-sync
1.94577 login-leap-session|authenticate
1.34612 login-leap-session|create|first-sync|finish
1.30648 login-leap-session|create|first-sync|sync
0.16763 login-leap-session|create|session-factory-create
0.16483 login-leap-session|create|session-factory-create|setup_soledad
0.00132 login-leap-session|create|session-factory-create|setup_keymanager
0.00099 login-leap-session|create|session-factory-create|other_misc
0.00011 login-leap-session|create|session-factory-create|instantiation
0.00010 login-leap-session|create|session-factory-create|prepare_variables
0.00002 login-leap-session|create|session-factory-create|create_leap_mailstore
```

The most striking thing is that from the whole time of **login-leap-session 4.76631s**

The most striking things are:
**login-leap-session|authenticate 1.94577s**
**login-leap-session|create|first-sync|finish 1.34612s**
**login-leap-session|create|first-sync|sync 1.30648s**
**login-leap-session|create|session-factory-create|setup_soledad 0.16483s**

These specific calls account for **4.7632s** of the **4.7663s** or more than **99%** of the login time

**Comment by bwagnerr** [comment]
We dug deeper into those 99% calls and came to the following:

These calls below are single calls to soledad and we didn't go deeper on them yet
**login-leap-session|create|first-sync|sync**
**login-leap-session|create|session-factory-create|setup_soledad**

This call is still inside the user agent code, so we broke the timings inside it:
**login-leap-session|create|first-sync|finish**

**0.00208** login-leap-session|create|first-sync|finish|generate-key|key-exists
**1.25289** login-leap-session|create|first-sync|finish|generate-key|send-key-leap
**1.25508** login-leap-session|create|first-sync|finish|generate_key
**0.00196** login-leap-session|create|first-sync|finish|create_account
**0.00135** login-leap-session|create|first-sync|finish|incoming_mail_fetcher
**0.00004** login-leap-session|create|first-sync|finish|start_services
**1.25859** login-leap-session|create|first-sync|finish

This shows that almost the whole time the first-sync|finish takes is spent on the send-key-leap piece. This is the code

```python
def generate_openpgp_key(self):
    key_present = yield self._key_exists(self._email)
    if not key_present:
        logger.info("Generating keys - this could take a while...")
        yield self._gen_key()
    yield self._send_key_to_leap()
```
Looking at this code, it uploads the public key on nicknym at every login, replacing the key stored there.
This should only be done when the key changes (for example when you generate a new key), so we can move it inside the "if not key_present" block and shave those seconds from the day to day login

---

Raw output
---

```python
1.92075 login-leap-session|authenticate
0.00009 login-leap-session|create|session-factory-create|prepare_variables
0.17449 login-leap-session|create|session-factory-create|setup_soledad
0.00002 login-leap-session|create|session-factory-create|create_leap_mailstore
0.00138 login-leap-session|create|session-factory-create|setup_keymanager
0.00075 login-leap-session|create|session-factory-create|other_misc
0.00008 login-leap-session|create|session-factory-create|instantiation
0.17704 login-leap-session|create|session-factory-create
1.30749 login-leap-session|create|first-sync|sync
0.00208 login-leap-session|create|first-sync|finish|generate-key|key-exists
1.25289 login-leap-session|create|first-sync|finish|generate-key|send-key-leap
1.25508 login-leap-session|create|first-sync|finish|generate_key
0.00196 login-leap-session|create|first-sync|finish|create_account
0.00135 login-leap-session|create|first-sync|finish|incoming_mail_fetcher
0.00004 login-leap-session|create|first-sync|finish|start_services
1.25859 login-leap-session|create|first-sync|finish
2.56619 login-leap-session|create|first-sync
2.74332 login-leap-session|create
4.66420 login-leap-session
```

**Comment by tuliocasagrande** [comment]
To wrap up, these are the longest metrics of single calls inside the login:

**41.18%** authenticate
**28.03%** sync
**26.86%** send-key-leap
**3.74%** setup_soledad
**99.81%** sum of these four

**100.00%** login-leap-session

We pinged @shyba to try to understand what makes a sync take that long without emails. But we consider this issue complete, moving to review.

**Comment by re-nobre** [comment]
Here is a chart with a good view of the calls inside the login-leap-session.
In orange we can see the calls with the biggest times. 

![tree-login-leap-session-5s](https://cloud.githubusercontent.com/assets/2657059/18216914/2a76c916-7130-11e6-9884-3e1142c9d1ea.png)

**Comment by tuliocasagrande** [comment]
Further actions described at #778

**Comment by kalikaneko** [comment]
@bwagner @tuliocasagrande 

I deeply think that your measurements are flawed somehow. I would like to collaborate finding the discrepancies and reducing the overall time, and also I'll try to persuade you that insisting in using the thradpools for everyhing is like putting the dirt under the carpet: in the end, it's giving you nice performance metrics for artificial use cases, but it ends up shooting you in the feet.

It is also in LEAP team interest that we deprecate leap_auth (and the other dependencies to keymanager and mail) asap (see #698).

See my gist: https://gist.github.com/kalikaneko/9e6aa00efc41f1881a61255c245c48bf

Two major points:

1. authentication in my tests takes, on average, 0.39 secs per use, using bonafide. That is *one order of magnitude lesser* that what you're measuring here, so it seems there is some big bottleneck in your setup.

2. It is true that deferring a blocking call to a threadpool gives a more advantageous situation with a single login or a few of them, but this setup is irreal and is hiding the contention (and memory) effects on the global threadpool. For instance:

  When NUM_THREADS >> concurrent_authenticating_users, the total time till authenticated is lesser than with bonafide (0.28). However, this better figure decreases drastically when the number of concurrent tasks approaches or is greater than the number of threads in the threadpool. You can test that as I did in the gist by manually adjusting the threadpool size, or by simply increasing the number of concurrent authentications. With concurrent users doubling the number of threads, you already have longer times with the threadpool solution.

  I'd like to remind you that you're sharing the same threadpool for many other things (crypto operations, serving the webapp etc), so it looks as a recipe to clog the threadpool with blocking calls and later complain that the whole solution doesn't scale.

  I would guess the longer times you see for bonafide come for setting up the pool of web clients, but that will be offset in the long run since those are reused.

**Comment by bwagnerr** [comment]
@kalikaneko Thanks for you comment! I'll test the gist here soon and see the results, remember that our test was inside the Pixelated User Agent so that also affects the results.

To answer some of your points:

- I totally agree with you that deferring to threads should be kept strictly to the operations that need it.

- We are deferring to thread the whole Soledad initialization, Keymanager initialization and the authentication, we should optimally break all of these processes in smaller pieces using deferreds and keep them on the main loop without threads.

- We should ultimately migrate to bonafide, this task was to test the hypothesis of performance gains using that instead of leap auth for 1 user and we didn't have improvements so we decided not to touch this for now.

Also, as we tested this, we have the code for using bonafide instead of leap.auth in the branch:

https://github.com/pixelated/pixelated-user-agent/tree/implement_bonafide

I'll bring the discussion up on the next group conversation of pix to integrate that branch in our master.
