### ISSUE TITLE
Mail in sent folder show up as "not signed"

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#775]
All my sent mails are shown as "not signed" on wazokazi and unstable.

**Comment by deniscostadsc** [comment]
We have removed the label in order to not show a wrong status. This doesn't really solve the problem but a proper solutions depends on not send emails individually for each recipient (I think Pixelated does this) and change something on LEAP side that I don't remember what it's exactly.

Because of this I'm closing this issue.
