### ISSUE TITLE
Stop sending public key on every login

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#778]
We found out on #772 that we're sending the user's public key to leap on every login:

```python
def generate_openpgp_key(self):
    key_present = yield self._key_exists(self._email)
    if not key_present:
        logger.info("Generating keys - this could take a while...")
        yield self._gen_key()
    yield self._send_key_to_leap()
```

We should send our public key to leap only when a new key is generated.

@kalikaneko @meskio do you agree we should restrict the key upload to when it's generated?

**Comment by kalikaneko** [comment]
yes

**Comment by tuliocasagrande** [comment]
@bwagnerr 
I updated the version of the mock library, but since then I've got the following error concerning the `stopService`. Can you check the `send_key_on_gen` branch when you find time?
Thaaaanks duuuude! 🎉 

```bash
[ERROR]
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/vagrant/service/test/unit/config/test_sessions.py", line 53, in test_that_close_stops_background_jobs
    mail_fetcher_mock.stopService.assert_called_once()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/mock/mock.py", line 915, in assert_called_once
    raise AssertionError(msg)
exceptions.AssertionError: Expected 'stopService' to have been called once. Called 0 times.

test.unit.resources.test_feedback_resource.TestFeedbackResource.test_sends_feedback_to_leap_web
```

**Comment by bwagnerr** [comment]
We confirmed the expected behaviour with leap, did the change and tested the impact on login time:

|Time Before  |Time After     |Improvement (%)|
|-----------------|-----------------|-----------------------|
|4.67              |3.36               |**38.9%**             |
|4.45              |3.13               |**42.2%**             |
|4.60              |3.32               |**38.6%**             |
|4.46              |3.76               |**18.6%**             |
|4.48              |3.11               |**44.0%**             |

(Measuring the HTTP request time)

**Comment by thaissiqueira** [comment]
The change is https://github.com/pixelated/pixelated-user-agent/commit/33901d27dafeb10b1eceafaf2ff2fbe3c76597ee

**Comment by thaissiqueira** [comment]
@bwagnerr brought a possible issue: If the key sending breaks the key will never been send.
