### ISSUE TITLE
Move to bitmask-dev

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#792]
LEAP asked us to move to bitmask-dev, so we need to accomplish the following steps:
- [x] Move leap.bonafide to leap.bitmask.bonafide
- [x] Move leap.keymanager to leap.bitmask.keymanager
- [x] Move leap.mail to leap.bitmask.mail
- [x] Drop leap.auth and replace it by leap.bitmask.bonafide

**Comment by tuliocasagrande** [comment]
@deniscostadsc and I started playing around a little bit with https://github.com/leapcode/bitmask-dev doing the most trivial thing: changing our import lines.

On 9356d5c3d4e940e5d4ebf1c851a16b43374a6bc3, we moved to bitmask.bonafide and we haven't encountered any issues.  So, for this one, we pushed to master.

On 0fa1a98b831f4b4995fd162c8fd6ff23731c5db4, we moved to bitmask.mail and we've got some unit tests failing about attachments:

```
twisted.trial.unittest.FailTest: Lists differ: [{'size': 202, 'ident': '1B478... != [{'size': 48, 'ident': '1B478D...
```

And an integration test failing:

```
twisted.trial.unittest.FailTest: No results returned from search
```


On d547bc5a4ab61ea773ebcc45134016c6326c3016, we moved to bitmask.keymanager and we've got many tests failing because of the gnupg library was missing (it's a known bug on Mac). We couldn't test on vagrant, because the pysqlcipher installation failed.

The last two commits are on the [move-to-bitmask](https://github.com/pixelated/pixelated-user-agent/compare/move-to-bitmask) branch.

**Comment by ayoyoness** [comment]
There are a couple of changes to [walk.py in leap.mail](https://github.com/leapcode/bitmask-dev/commit/18194c2a64a38a07652eb24a6e89ec40d32e7e57) as part of the fix for the email delivery notification/bounce messages attachment problems.
Now, we get the actual payload size (reason for the unit test failure)... we can just replace those with the actual size (48).

The integration test failure is because we don't have the body charset anymore... so some encoding will be wrong. That is the case for the base64 in the test... ie we index the wrong body, and therefore cannot search for the original one...
I already pinged @kalikaneko to provide a way to get the charset.

The `content_doc.content_type` in [this line](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/adapter/mailstore/leap_mailstore.py#L333) needs to include the charset as well, and it should be green again.

**Comment by ayoyoness** [comment]
PR to retrieve charset: https://github.com/leapcode/bitmask-dev/pull/3

**Comment by ayoyoness** [comment]
What's left:

- [ ] fix CI
- [ ] PR merge 
- [ ] restore test_search or merge [move-to-bitmask](https://github.com/pixelated/pixelated-user-agent/compare/move-to-bitmask)

**Comment by tuliocasagrande** [comment]
75b633a already moved everything to bitmask, so we can discard the [move-to-bitmask](https://github.com/pixelated/pixelated-user-agent/compare/move-to-bitmask) branch

We also have this task left:
- [ ] Drop leap.auth and replace it by leap.bitmask.bonafide

**Comment by tuliocasagrande** [comment]
PR merged https://github.com/leapcode/bitmask-dev/pull/3#issuecomment-254936979

**Comment by kalikaneko** [comment]
something that I liked of leap.auth is that it had nice tests, I want to port them to bitmask.bonafide

**Comment by re-nobre** [comment]
we have three things breaking our go-ci that can be related with this card:
- merge-leap-soledad::merge
- soledad::tests
- bitmask-dev:tests
@ayoyoness  can you confirm that?

**Comment by ayoyoness** [comment]
yes, I confirm apart from the merge-leap-soledad. That is unrelated but is just blocked because the soledad tests is red.

**Comment by rdevries-thoughtworks** [comment]
There are a few issues left:

- I tested manually, and `pixelated-register` is not working
- there is not test for the `pixelated.register.register` method (no unit test and not end-to-end test)
- `leap.auth` is still required by the locustfile and by the `create_users` script

**Comment by rdevries-thoughtworks** [comment]
I reviewed the 3 items from [the previous comment](https://github.com/pixelated/pixelated-user-agent/issues/792#issuecomment-257908372) and closed this issue.
