### ISSUE TITLE
Streaming: test Soledad changes

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#799]
@shyba made some change to improve the streaming on soledad.
The changes can be seen here: https://0xacab.org/leap/soledad/merge_requests/27
We need to test it with pixelated.

**Comment by tayanefernandes** [comment]
We created a vagrant inside soledad repo, and we trying to use the debian-package.sh from thoughtworks-ci-config to generate a package and install it locally.

**Comment by tayanefernandes** [comment]
We've managed to package the soledad using the https://0xacab.org/shyba/soledad/commits/feature/streaming_encrypter branch:

**Comment by tayanefernandes** [comment]
We created 10 new users in unstable (_streamingtest_) and we're going to execute the following test strategy with and without new soledad changes to compare the results:

 - execute the script `concurrent_logins.sh` to measure the login time
 - send 10 emails to each user and execute the `concurrent_logins.sh` again, to measure the login time with emails.

We need to think in a strategy to test big attachments, @pixelated/core do you have any suggestion?

**Comment by rdevries-thoughtworks** [comment]
> `pixssh go-agent4.pixelated-project.org`

Side note: I guess the package creation didn't work on a Mac, but I think logging in to a go agent (or server, for that matter) is generally not a good plan. Creating the package from a vagrant box or unstable would be better.

**Comment by tuliocasagrande** [comment]
You're right, @rdevries-thoughtworks 
We were having some problems to generate the package and couldn't come up with a better/faster approach.

**Comment by tayanefernandes** [comment]
We generated these graphics after our tests:
 - Login with 10 users without emails (3 times)
 - Login with 10 users with 10 emails (3 times)
[Soledad Streaming Test - Sheet2.pdf](https://github.com/pixelated/pixelated-user-agent/files/572449/Soledad.Streamin.Test.-.Sheet2.pdf)

**Comment by deniscostadsc** [comment]
To achieve the results above, we updated the three packages of Soledad (server, common and client). Then, we deleted the user databases on Couchdb. As an effect of that deletion, the users can not login to Pixelated running on unstable. We created new users to test if the problem only happen with old users, but those users also cannot login into Pixelated.

We tried to login running a local instance of Pixelated, with that approach old and new users can login into Pixelated normally. 

As we discussed with @shyba, this could be a simple (and quick and dirty) solution to migrate user databases on the provider side. So we'll try to fix unstable.

**Comment by rdevries-thoughtworks** [comment]
> Soledad Streaming Test - Sheet2.pdf

@tayanefernandes Can you share the code generating the test committed to the repo? And the raw measurements?

**Comment by tayanefernandes** [comment]
@rdevries-thoughtworks
 https://docs.google.com/a/thoughtworks.com/spreadsheets/d/1JbMS9xG-_4J1X3b5M9rE7mh3uRHNmftsxnZ6keYlnn4/edit?usp=sharing

And we used the `concurrent_logins.sh` script to generate the results.

**Comment by tayanefernandes** [comment]
We noticed that we didn't install the soledad client and because of that we were not really syncing, therefore our [measurement](https://github.com/pixelated/pixelated-user-agent/issues/799#issuecomment-258522811) is not valid.
Besides that, the `concurrent_logins.sh` doesn't measure the syncing time, we should have use `concurrent_logins.rb` to have the correct value.

**Comment by deniscostadsc** [comment]
After we realized our mistake we fixed it, installing soledad client on our environment. But user still not been able to send/receive emails. Probably because that changes on Soledad.

And to really fix the problem we have to dig deep on it. This could take some time, because we don't know if we have to change Soledad code. Actually, we already have to do a small change on a import, because they change the API. And more changes that doesn't cause exceptions could be hidden. After our upgrade, Soledad stopped creating logs, what get things even more difficult.

Maybe this could be related with the migration task, after Soledad update to the new code. What should we do with this card? Expand the card to see how to fix things for the users after the upgrade or stop it? Should this investigation be part of migration task mentioned on the weekly pad?

**Comment by rdevries-thoughtworks** [comment]
> Besides that, the concurrent_logins.sh doesn't measure the syncing time, we should have use concurrent_logins.rb to have the correct value.

How are these scripts different? From the name they look like they're doing the same thing... Should we rename at least one of them?

**Comment by thaissiqueira** [comment]
> What should we do with this card? Expand the card to see how to fix things for the users after the upgrade or stop it? Should this investigation be part of migration task mentioned on the weekly pad?

Since the goal is measure the improvements I think that fix this problem is out of scope of this issue. I guess that the best approach is report the error and relate both issues.

**Comment by deniscostadsc** [comment]
> How are these scripts different? From the name they look like they're doing the same thing... Should we rename at least one of them?

They do almost the same thing. The difference is that the Ruby script wait for th interstitial page.

**Comment by tayanefernandes** [comment]
We noticed that Soledad process is not running properly, because it was having problems with this file /etc/init.d/soledad-server. We commented the problematic line, but after that we got the error: No such WSGI application: 'leap.soledad.server.application'.
We are still investigating this.

**Comment by deniscostadsc** [comment]
We are moving that card back to the backlog, because it's not priority for this week. So we'll document what we got so far, so people can continue from where we stop.

We were trying to compare the performance between old and new streaming approaches. The get the numbers for new approach we installed debian and python packages for Soledad common, client and server. The git commit used for that was [78cd816c](https://0xacab.org/shyba/soledad/commit/78cd816cddfd76ee76ba1d372fb44fb41e717469), from @shyba changes on his fork.

After restarting Soledad process using systemd, we noticed that systemd didn't show any error but the process wasn't running. So to debug that we tried to run `/etc/init.d/soledad-server` manually just to check what was going on. We notice the that script was exiting before really starting the process, so we commented the "problematic" line. But on the second try we realized that the Soledad WSGI application was been found. We couldn't even import `leap.soledad.server` on Python REPL. Probably because the way we installed Soledad python packages on the virtualenv.

```
root@unstable1:~# . /usr/share/python/pixelated-user-agent/bin/activate
(pixelated-user-agent)root@unstable1:~# pip freeze | grep soledad
-e git+https://0xacab.org/shyba/soledad.git@78cd816cddfd76ee76ba1d372fb44fb41e717469#egg=leap.soledad.client&subdirectory=client
-e git+https://0xacab.org/shyba/soledad.git@78cd816cddfd76ee76ba1d372fb44fb41e717469#egg=leap.soledad.common&subdirectory=common
-e git+https://0xacab.org/shyba/soledad.git@78cd816cddfd76ee76ba1d372fb44fb41e717469#egg=leap.soledad.server&subdirectory=server
(pixelated-user-agent)root@unstable1:~#python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import pprint
>>> pprint.pprint(sys.path)
['',
 '/root/src/leap.soledad.common/common/src',
 '/root/src/leap.soledad.server/server/src',
 '/root/src/leap.soledad.client/client/src',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']
```

Unfortunately, because of this problem we could not move on on this test.

**Comment by rdevries-thoughtworks** [comment]
I've put back the 'development' label so we won't forget discussing this issue in today's standup. We might want to remove it afterwards again.

**Comment by deniscostadsc** [comment]
We decided to unprioritize this card comparing with the migration, we had a few things to share/ask to Shyba about:

- Changes on Soledad logs;

- Problema starting Soledad;
