### ISSUE TITLE
Allow decryption from more than one key

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#850]
**Narrative:**
As a pixelated/leap user, when I renew my soon-to-expire key, I want to have both key pairs (old and new) in  my key ring and be able to decrypt using both, so that I am able to decrypt my emails regardless of which of my old or new key are used by the sender.

**ACs:**
when my key pair is renewed, 
- I am able to read in the UA, new emails encrypted using my new key.
- I am able to read in the UA, new emails encrypted using my old key.
- I am able to read my old emails.

This an extension of #815

**Comment by ayoyoness** [comment]
This is the famous ** interoperability **  
@kalikaneko  ;-)

**Comment by ayoyoness** [comment]
Tasks:
- [ ] ensure two private keys are allowed in keymanager: one active and one inactive
- [ ] implement decryption with inactive key, when with the active one fails
- [ ] adapt invocation in the UA login process to renew key 1 month (for now) ahead of the current key expiry date

**Comment by thaissiqueira** [comment]
What we are calling 'inactive' key? Revoked and expired?
Is it ok decrypt using an inactive key? For me (without any previous search to say it) it sounds like some vulnerable thing. It is?

**Comment by zariye** [comment]
@thaissiqueira no 'inactive' key is only a wording leap is using, it does not indicate anything about expire or revocation, buuuuut it says which key is supposed to be used here. Before this feature it was only possible to use active keys, that should be changed in order to decrypt mails which has been encrypted to the previous key before the new active one was created and not been decrypted in this 'overlap' timeframe.

**Comment by thaissiqueira** [comment]
@zariye @olabini thank you for the answers.

**Comment by zariye** [comment]
So as @ayoyoness promised in the weekly we will update this card to inform you about the discussion we just had with @varac: 

As you already might know keys created by the keymanager get a default expire_date which is one year after the creation date of the key. We decided therefore to start with the key renewal two month and less before the key will get expired, because a key will be only possible to get renewed when a user is logged in. We discussed that a buffer of two month does makes sense. Pls tell us if u want to argue about that.

**Comment by bwagnerr** [comment]
I can't review this issue before #855 is merged (to leap or to our fork)

It looks like we also shouldn't merge the branch key_expiry while the PRs are pending (because the changes will break without the earlier PRs)

I'll block this issue until we figure out what to do with the PRs.

**Comment by thaissiqueira** [comment]
Blocked by merge happening in #815

**Comment by zariye** [comment]
https://0xacab.org/leap/bitmask-dev/merge_requests/48
