### ISSUE TITLE
Identify where in the flow of sending/receiving a big attachment vanishes

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#854]
What
--
After the investigations on #814, we found some blockers to bigger attachments that we'll have to fix. Removing those blockers temporarily, the attachment was sent successfully (without errors on sending), but it still didn't arrive.

Definition of done
--
We have a list of needed changes so a big attachment that we send through pixelated arrives for the end user (also on pixelated)

**Comment by thaissiqueira** [comment]
We found that even though we were not seeing the error, it was happening.

```python
Unhandled error in Deferred:
```
Inspecting the problem, we found the real culprit:
```
2016-11-28 16:41:52 [stdout] INFO <twisted.python.failure.Failure twisted.mail.smtp.SMTPDeliveryError: 552 5.3.4 Error: message file too big
2016-11-28 16:41:52 [stdout] INFO >>> DATA
2016-11-28 16:41:52 [stdout] INFO <<< 354 End data with <CR><LF>.<CR><LF>
2016-11-28 16:41:52 [stdout] INFO >>> .
2016-11-28 16:41:52 [stdout] INFO <<< 552 5.3.4 Error: message file too big
2016-11-28 16:41:52 [stdout] INFO >
```

This error is not being treated or reported to the user and we are not capturing it or treating it in any way.

We'll create an issue to handle this error, but for the exploration we increased the postfix message size limit temporarily so we can go deeper.

**Comment by rdevries-thoughtworks** [comment]
Do we know why this error is not handled/reported? Can we figure that out in the context of this issue, or should we create a new one for it? I do think it's very important to figure this out, because otherwise we might be missing other error messages too.

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks 
We'll create new issues for the problems we find here, for now we increased the file size so we wouldn't see this error anymore and can move on with the issue, but wrote here so we remember to create an issue for that later.

The error pops up on the mail sender, it is not on the normal application flow and it doesn't have a proper errBack, because of that twisted throws an "Unhandled Error" on the logs. This would optimally be treated on leap.mail and a signal would be sent in case of error that we could catch and raise a proper error.

**Comment by thaissiqueira** [comment]
We are moving to work on the #856 because it is blocking us.

**Comment by thaissiqueira** [comment]
With the last change (increasing the postfix size limit) we successfully received an email with 10MB attachment.

We noticed that the machine froze in some moments during the receiving sync.

Our next step will be to try to send a 25MB attachment and after that we intend to start measuring the machine resources usage.

**Comment by thaissiqueira** [comment]
Test with 25MB attachment

**Manual modifications**
- Front-end ajax timeout increased to 10 minutes
- Front-end attachment limit increased to 50mb
- Postfix message limit increased to 50mb

**Outcome**
- Sending the mail worked successfully
- Receiving the mail on the provider and saving it on CouchDB worked successfully
- Receiving the mail on the client **did not work**:
  - The synchronisation was successful
  - The decryption of the received mail caused OOM (out of memory killer) to be called by the OS, (note that this happened on a 1GB RAM Vagrant)

With this outcome, we have two possible paths:
- Fix the problems we found and clear the way to focus on the memory problem
- Measure the memory problems before fixing anything, to have a better idea of the effort we'll need to solve big attachments completely

**Comment by varac** [comment]
@thaissiqueira @bwagnerr : Were you using the same pixelated-server instance on your local vagrant box for sending and recieving ? Meaning, did you restart it in between to get rid of possible mem leakage from sending ? Did you run in multiuser or single user mode ?

Could you pls share the overall memory consumption before and during the test ?

Also, not sure you are aware of the [overall memory consumption graph for the pixelated-user-agent on unstable.pix](https://unstable.pixelated-project.org/pnp4nagios/index.php/graph?host=unstable1.unstable.pixelated-project.i&srv=Pixelated_Stats) that can get useful for mapping big changes in mem usage. (I think doing it on vagrant is probably better I just wanted to let you know).

Kali was asking me why we are spending time on measuring the already deprecated soledad before merging the streaming branch, and not simply start with the streaming branch as baseline. That could be a way not wasting time on fixing stuff that might already be fixed/improved with the streaming branch.

**Comment by thaissiqueira** [comment]
@varac 
> Were you using the same pixelated-server instance on your local vagrant box for sending and recieving ?

Yes

> Meaning, did you restart it in between to get rid of possible mem leakage from sending ?

No, we didn't restart it.

> Did you run in multiuser or single user mode ?

WE ran it on multiuser mode.

> Could you pls share the overall memory consumption before and during the test ?

That that will be our next step.

> Also, not sure you are aware of the overall memory consumption graph for the pixelated-user-agent on unstable.pix that can get useful for mapping big changes in mem usage. (I think doing it on vagrant is probably better I just wanted to let you know).

Yes, we are and thank you for reminding us.

> Kali was asking me why we are spending time on measuring the already deprecated soledad before merging the streaming branch, and not simply start with the streaming branch as baseline. That could be a way not wasting time on fixing stuff that might already be fixed/improved with the streaming branch.

Yes, you are right. Our plan for the next step on the memory usage analysis os use the streaming branch to understand how much we can improve with that.

**Comment by bwagnerr** [comment]
| Problems found | Possible solutions |
|----------------------|------------------------|
|Front-end ajax timeouts when sending|The user-agent should keep the connection alive while processing the request (HTTP KeepAlive)|
|Front-end attachment limit is set to 5MB|Increase the attachment limit to 25MB|
|Postfix message size limit defaults to 10MB|Increase the postfix limit on leap_platform to 40MB|
|python-gnupg is printing the whole encrypted message to the log|Filter the gnupg log or set a different log level to it|
|Out of memory problem|Fixing the problems above, we can start exploring this|

Front-end timeout when sending big mails
---
When sending a mail with big attachment, the sending might take more than the 60 seconds defined for the front-end ajax request timeout. To have 25MB attachments we need to solve this problem.

The timeout is defined here [monitoredAjax](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/js/helpers/monitored_ajax.js#L30)
For more context see [this comment](https://github.com/pixelated/pixelated-user-agent/issues/814#issuecomment-262838558)

Front-end attachment limit is set to 5MB
---
We need to increase this if we want to send 25MB attachments, pretty straighforward.
The limit is defined here [ATTACHMENT_SIZE_LIMIT](https://github.com/pixelated/pixelated-user-agent/blob/fc4fe7f3efc69a04a7cd11d2a8ec98a68ec76e4d/web-ui/app/js/mail_view/ui/attachment_list.js#L45)

Postfix message size limit defaults to 10MB
---
In order to accomodate 25MB attachments, we have to increase the message limit on postfix to 40MB (this considers a 25MB attachment plus 1MB headers and body, encrypted and armored that amounts to 35MB plus 4MB as a safety margin to account for encoding and such)

We have to change on the postfix conf the following option:
```message_size_limit=<new_limit>```

python-gnupg is printing the whole encrypted message to the log
---
When python-gnupg encrypts a message, it prints the whole encrypted content to the log (for debugging purposes), this froze and blocked the application for a little while for 10MB and for a longer time for 25MB. We have to filter this output or decrease the log level of gnupg to prevent this behaviour.

Out of memory problem
---
When testing with 25MB, the sending worked, the syncing worked and we got OOM (Out of memory) when trying to decrypt the incoming mail (raw mail including headers encrypted to the user public key)

The biggest hurdle is that the user-agent has a baseline memory usage of around 300MB and a 25MB attachment (around 35MB encrypted and armored), even it at the end of the decryption process we have an encrypted and a plain-text copy of it, would not account for enough increase in memory to account for the OOM (The UA was already asking for 1.6GB of memory when the OS killed it).

The streaming changes would solve the problem if it happened on the symmetric encryption process, but this happened when decrypting the assymetrically encrypted raw mail. So now that we cleared the other hurdles, we can focus on digging deeper into this problem and find what accounts for the rest of the memory increase.

**Comment by thaissiqueira** [comment]
We have a new milestone as an outcome of this issue:
https://github.com/pixelated/pixelated-user-agent/milestone/3

We are closing this and referencing this on the other issues
