### ISSUE TITLE
Key renewal and decryption from both keys

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#855]
To keep track of https://0xacab.org/leap/bitmask-dev/merge_requests/47

**Comment by ayoyoness** [comment]
this is already part of https://0xacab.org/leap/bitmask-dev/merge_requests/48 and is reviewed there... so closing.

**Comment by re-nobre** [comment]
hey, @ayoyoness!
I'm confusing here. 
As the PR is not accepted yet, this issue is not done and we shouldn't close it.

**Comment by ayoyoness** [comment]
just confirming, this is definitely part of #857
and can be closed.

**Comment by re-nobre** [comment]
Hey, @ayoyoness!

Thank you for the new comment, but I'm still confused.

If this specific issue is part of the other issue that is opened and blocked because of a PR that is not accepted yet, this issue is not done yet.

Maybe there is not that we can do in this card, only wait. If it's the case, we can put the blocked label. But until we won't have the "Key renewal and decryption from both keys" possible, this issue can't be considerer done.

**Comment by ayoyoness** [comment]
I understand what you mean but this is not that issue. This is an issue to track the PR related to that issue. That PR  can be tracked by #857... put simply, this is redundant.

**Comment by ayoyoness** [comment]
Archiving this as we are tracking it in #857
