### ISSUE TITLE
Filter python-gnupg encrypted message printing to the log

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#862]
What
---
When python-gnupg encrypts a message, it prints the whole encrypted content to the log (for debugging purposes), this froze and blocked the application for a little while for 10MB and for a longer time for 25MB. We have to filter this output or decrease the log level of gnupg to prevent this behaviour.

**Possible solution**: Filter the gnupg log or set a different log level to it

Definition of done
---
When a mail is sent, the encrypted data is not printed to the log by gnupg

**Comment by tuliocasagrande** [comment]
We've checked the logs before and after https://github.com/pixelated/pixelated-user-agent/commit/b4735378f343fbcb695956a161b21076254de79f and this are our findings:

- The encrypted message is not being printed anymore, even with the `--debug` flag.
- Some `BEGIN PGP PRIVATE KEY BLOCK` were still being printed even with the filter we have. This commit also removed those prints.

However, should we find another way to suppress the encrypted message and private key from being printed instead of hardcoding the python-gnupg logging level?

**Comment by ayoyoness** [comment]
This story is about preventing huge blocks of encrypted stuff overcrowding the log... it is somewhat related to leaking private keys in the log but not exactly about that. Anything that clutters the log needs to be cut out, I found out that most of those are on INFO loglevel ny python-gnupg, so I simply raised it to WARNING.

**Comment by deniscostadsc** [comment]
@ayoyoness 

We had a discussion here and we believe that the best way to solve this problem is to change the logging level of encrypted content to debug. To achieve this we have to change that on our fork o python-gnupg and then PR this against Isis' repo.

Regarding logging private key, we also think that should be done changing log level to debug on that specific part.

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
