### ISSUE TITLE
Unable to read my mails

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#953]
Hi, I logged in today and can read my mails :/
The mail window is just blank, and I got a notice "A Timeout occurred."

see attached screenshot
![screenshot_2017-02-01_11-20-43](https://cloud.githubusercontent.com/assets/488213/22503183/daa120a4-e870-11e6-8972-748f96a3f1bf.png)

**Comment by varac** [comment]
Regarding the severity of this bug I made it a candidate.

**Comment by varac** [comment]
Clicking on other mails I got another notice: "Could not fetch messages"

**Comment by varac** [comment]
After re-logging in, I can see the mail but it *really* takes a long time to display them, like 30secs per mail. In the log I see a lot of errors that are related to #908

**Comment by tuliocasagrande** [comment]
Hey @varac,

Since we created more specific issues about the errors we faced last week, I don't think there's much left to be done at this one.

Following issues that handle the problems separately:
https://github.com/pixelated/pixelated-user-agent/issues/957
https://github.com/pixelated/pixelated-user-agent/issues/952

===

Concerning the errors you've seen that are related to #908, those are the emails you received during the time you got your key expired. Unfortunately they are irrecoverable, since they failed to encrypt, but were deleted from the incoming queue nevertheless. On #908, we fixed to not save this unreadable blob to Soledad. We still need to perform a clean in your account, to delete this kind of email and stop messing with the logs.
